spring:
  thymeleaf:
    templateResolverOrder: 1
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=db_patients
    username: sa
    password: myPassw0rd
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        temp:
          use_jdbc_metadata_defaults: false